### ISSUE TITLE
[ISSUE] Fast/Prompt doesn't roll initiative for NPCs

### ISSUE THREAD

**Issue by weepingminotaur** [veevelder/quick-combat#37]
When the Fast/Prompt initiative option is enabled, adding NPCs to the combat tracker no longer auto-rolls their initiative. Possibly a recent Foundry or system change broke the feature?

I have reproduced this using Foundry v11 build 308, Pathfinder 2e 5.4.4, in a blank world with only Quick Combat, libWrapper, and Socketlib enabled.

**Comment by veevelder** [comment]
just making sure I understand this correctly, when adding npcs to the combat tracker and before starting combat, the npcs are no longer auto rolling initiative.

If thats the case, this is by design now, after adding the group rolling feature I needed to change how things were automated. the initiative rolling now happens at combat start not when adding tokens to the combat tracker.

If this is not the case then can you provide any console messages when attempting to start combat. (hit F12 then navigate to the `Console` tab, copy the contents and paste them here)
